const CONNECT = 1010;
const SET_SHARE_ID = 1020;
const SET_SHARE_DATA = 1030;

const GET_COUNT_OF_CONNECTED_DEVICES = 1000;
const GET_LIST_OF_CONNECTED_DEVICES_NAME = 1002;

const GET_TREE_OF_FOLDERS = 2000;
const UPDATE_NAME_OF_FOLDER = 2001;
const DELETE_FOLDERS = 2002;
const ADD_FOLDERS = 2003;

const RES_GET_TREE_OF_FOLDERS = 3000;
const RES_UPDATE_NAME_OF_FOLDER = 3001;
const RES_DELETE_FOLDERS = 3002;
const RES_ADD_FOLDERS = 3003;

const NOT_SHARE_DEVICE = 4000;
const INVALID_JSON = 4001;

const SEND_FILE_STAT = 7000;
const SEND_FILE = 7001;

module.exports = {
  CONNECT,
  SET_SHARE_ID,
  SET_SHARE_DATA,

  GET_COUNT_OF_CONNECTED_DEVICES,
  GET_LIST_OF_CONNECTED_DEVICES_NAME,

  GET_TREE_OF_FOLDERS,
  UPDATE_NAME_OF_FOLDER,
  DELETE_FOLDERS,
  ADD_FOLDERS,

  RES_GET_TREE_OF_FOLDERS,
  RES_UPDATE_NAME_OF_FOLDER,
  RES_DELETE_FOLDERS,
  RES_ADD_FOLDERS,

  NOT_SHARE_DEVICE,
  INVALID_JSON,

  SEND_FILE_STAT,
  SEND_FILE,
};
