pipeline {
  agent none
  options { skipDefaultCheckout(false) }
  stages {
    stage('Docker Build') {
      agent any
      steps {
        sh 'docker build -t field-pjt-back:latest ./Backend'
        // sh 'docker build -t field-pjt-front:latest ./Web'
        sh 'docker build -t field-pjt-fileserver:latest ./FileServer'
      }
    }
  
    stage('Docker Container rm') {
      agent any 
      steps {
        sh 'docker ps -f name=field-pjt-back -q | xargs --no-run-if-empty docker container stop'
        sh 'docker container ls -a -name=field-pjt-back -q | xargs -r docker container rm'

        // sh 'docker ps -f name=field-pjt-front -q | xargs --no-run-if-empty docker container stop'
        // sh 'docker container ls -a -name=field-pjt-front -q | xargs -r docker container rm'

        sh 'docker ps -f name=field-pjt-fileserver -q | xargs --no-run-if-empty docker container stop'
        sh 'docker container ls -a -name=field-pjt-fileserver -q | xargs -r docker container rm'

        sh 'docker ps -a -f "status=created" -f "status=exited" -q | xargs -r docker container rm'
        sh 'docker images -f "dangling=true" -q | xargs -r docker rmi'
      }
    }
    
    stage('Docker run') {
      agent any
      steps {
        sh 'docker run -d --name field-pjt-back \
            -v /volumes/back_home/profile:/volumes/profile \
            --network field-network \
            field-pjt-back:latest' 
        sh 'docker run -d --name field-pjt-fileserver \
            -p 8002:9002 \
            -p 8003:9003 \
            -v /volumes/fileServer_home:/volumes \
            -v /volumes/web_home/key:/volumes/key \
            --network field-network \
            field-pjt-fileserver:latest'
        // sh 'docker run -d --name field-pjt-front \
        //     -p 80:80 \
        //     -p 443:443 \
        //     -v /volumes/web_home:/volumes \
        //     -v /volumes/back_home/profile:/volumes/profile \
        //     -v /volumes/web_home/log:/var/log/nginx/host.access.log \
        //     --network field-network \
        //     field-pjt-front:latest'
        
       }
    }
  }
}
