pipeline {
  agent none
  stages {
    stage('Docker Build') {
      agent any
      steps {
        sh 'pwd'
        sh 'docker build -t field-pjt-back:latest ./Backend'
      }
    }
  
    stage('Docker Container rm') {
      agent any 
      steps {
        sh 'docker ps -f name=field-pjt-back -q | xargs --no-run-if-empty docker container stop'
        sh 'docker container ls -a -name=field-pjt-back -q | xargs -r docker container rm'

        sh 'docker ps -a -f "status=exited" -q | xargs -r docker container rm'
        sh 'docker images -f "dangling=true" -q | xargs -r docker rmi'
      }
    }
    
    stage('Docker run') {
      agent any
      steps {
        sh 'docker run -d -p 8080:3000 --name field-pjt-back field-pjt-back:latest' 
      }
    }
  }
}
