const GET_COUNGT_OF_CONNECTED_DEVICES = 1000;
const GET_LIST_OF_CONNECTED_DEVICES_NAME = 10002;

const GET_TREE_OF_FOLDERS = 2000;
const UPDATE_NAME_OF_FOLDER = 2001;
const DELETE_FOLDERS = 2002;
const ADD_FOLDERS = 2003;

module.exports = {
  GET_COUNGT_OF_CONNECTED_DEVICES: GET_COUNGT_OF_CONNECTED_DEVICES,
  GET_COUNT_OF_ALL_CONNECTED_DEVICES: GET_COUNT_OF_ALL_CONNECTED_DEVICES,
  GET_LIST_OF_CONNECTED_DEVICES_NAME: GET_LIST_OF_CONNECTED_DEVICES_NAME,

  GET_TREE_OF_FOLDERS: GET_TREE_OF_FOLDERS,
  UPDATE_NAME_OF_FOLDER: UPDATE_NAME_OF_FOLDER,
  DELETE_FOLDERS: DELETE_FOLDERS,
  ADD_FOLDERS: ADD_FOLDERS,
};
