const CONNECT = 1010;
const SET_SHARE_ID = 1020;

const GET_COUNT_OF_CONNECTED_DEVICES = 1000;
const GET_LIST_OF_CONNECTED_DEVICES_NAME = 1002;

const GET_TREE_OF_FOLDERS = 2000;
const UPDATE_NAME_OF_FOLDER = 2001;
const DELETE_FOLDERS = 2002;
const ADD_FOLDERS = 2003;

const RES_GET_TREE_OF_FOLDERS = 3000;
const RES_UPDATE_NAME_OF_FOLDER = 3001;
const RES_DELETE_FOLDERS = 3002;
const RES_ADD_FOLDERS = 3003;

module.exports = {
  CONNECT: CONNECT,
  SET_SHARE_ID: SET_SHARE_ID,

  GET_COUNT_OF_CONNECTED_DEVICES: GET_COUNT_OF_CONNECTED_DEVICES,
  GET_LIST_OF_CONNECTED_DEVICES_NAME: GET_LIST_OF_CONNECTED_DEVICES_NAME,

  GET_TREE_OF_FOLDERS: GET_TREE_OF_FOLDERS,
  UPDATE_NAME_OF_FOLDER: UPDATE_NAME_OF_FOLDER,
  DELETE_FOLDERS: DELETE_FOLDERS,
  ADD_FOLDERS: ADD_FOLDERS,

  RES_GET_TREE_OF_FOLDERS: RES_GET_TREE_OF_FOLDERS,
  RES_UPDATE_NAME_OF_FOLDER: RES_UPDATE_NAME_OF_FOLDER,
  RES_DELETE_FOLDERS: RES_DELETE_FOLDERS,
  RES_ADD_FOLDERS: RES_ADD_FOLDERS,
};
